cart/urls.py

from django.urls import path

from cart.views import *

urlpatterns = [
    path('cart/', cart, name='cart'),
    path('add_cart/',add_cart, name='add_cart'),
    path('count_cart/',count_cart, name='count_cart'),
    path('change_cart/<int:id>/',change_cart, name='change_cart'),
    path('del_cart/<int:id>/',del_cart, name='del_cart'),

]

goods/urls.py

from django.urls import path

from goods.views import *
# detail,goodlist
urlpatterns = [
    path('index/', index, name='index'),
    path('logout/', logout, name='logout'),
    path('detail/<int:id>/', detail, name='detail'),
    path('goodlist/', goodlist, name='goodlist'),

]

ttsx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static

from ttsx.settings import MEDIA_URL,MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('user.urls','user'), namespace='user')),
    path('goods/', include(('goods.urls','goods'), namespace='goods')),
    path('cart/', include(('cart.urls','cart'), namespace='cart')),
    path('order/', include(('order.urls','order'), namespace='order')),

]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

user/urls.py

from django.urls import path

from user.views import *

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login, name='login'),

    # 用户中心
    path('user_center_info/', user_center_info, name='user_center_info'),
    path('user_center_order/', user_center_order, name='user_center_order'),
    path('user_center_site/', user_center_site, name='user_center_site'),

]

cart/models.py
from django.db import models

from goods.models import Goods
from user.models import User


class ShoppingCart(models.Model):
    """
    购物车
    """
    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, verbose_name='商品', on_delete=models.CASCADE)
    nums = models.IntegerField(default=0, verbose_name='数量')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')
    is_select = models.BooleanField(default=True)

    class Meta:
        db_table = 'f_shopping_cart'

user/models.py

from django.db import models


class User(models.Model):
    """
     用户表
    """
    username = models.CharField(max_length=20, unique=True, null=True, blank=True, verbose_name="姓名")
    password = models.CharField(max_length=255, verbose_name="密码")
    birthday = models.DateField(null=True, blank=True, verbose_name="出生年月")
    GENDER = (
        ("male", "男"),
        ("female", "女")
    )
    gender = models.CharField(max_length=6, choices=GENDER, default="female",
                              verbose_name="性别")
    mobile = models.CharField(null=True, blank=True, max_length=11, verbose_name="电话")
    email = models.EmailField(max_length=100, null=True, blank=True, verbose_name="邮箱")

    class Meta:
        db_table = 'f_user'

class UserToken(models.Model):
    token = models.CharField(max_length=100, unique=True, null=False,
                             verbose_name='token标识符')
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    out_time = models.DateTimeField(null=True)

    class Meta:
        db_table = 'my_token'

class UserAddress(models.Model):
    """
    收货地址表
    """
    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    province = models.CharField(max_length=100, default='', verbose_name='省份')
    city = models.CharField(max_length=100, default='', verbose_name='城市')
    district = models.CharField(max_length=100, default='', verbose_name='区域')
    address = models.CharField(max_length=100, default='', verbose_name='详细地址')
    signer_name = models.CharField(max_length=20, default='', verbose_name='签收人')
    signer_mobile = models.CharField(max_length=11, default='', verbose_name='电话')
    signer_postcode = models.CharField(max_length=11, default='', verbose_name='邮编')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')

    class Meta:
        db_table = 'f_user_address'






cart/views.py
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from cart.models import ShoppingCart


def cart(request):
    if request.method == 'GET':
        return render(request, 'cart.html')


def add_cart(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        goods_count = len(session_goods)
        return JsonResponse({'code': 200, 'msg': '请求成功', 'goods_count': goods_count})

    if request.method == 'POST':
        goods_id = int(request.POST.get('goods_id'))
        nums = int(request.POST.get('nums'))
        goods_list = [int(goods_id), int(nums), 1]
        session_goods = request.session.get('goods')

        if session_goods:
            # 添加或者修改
            flag = False
            for goods in session_goods:
                # goods为[goods_id, nums, is_select]
                if goods[0] == goods_id:
                    goods[1] += nums
                    flag = True
            # 添加
            if not flag:
                session_goods.append(goods_list)
            request.session['goods'] = session_goods
            # session中保存的商品的个数
            goods_count = len(session_goods)
        else:
            # 第一次添加商品到session中时，保存键值对
            # 键为goods，值为[[id, nums, is_select], [id, nums, is_select]]
            request.session['goods'] = [goods_list]
            goods_count = 1
        return JsonResponse({'code': 200, 'msg': '请求成功', 'goods_count': goods_count})


def count_cart(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        count = len(session_goods) if session_goods else 0
        return JsonResponse({'code': 200, 'msg': '请求成功', 'count': count})


def change_cart(request):
    if request.method == 'POST':
        # 获取前端Ajax传递的goods_id,is_select,nums
        goods_id = int(request.POST.get('goods_id'))
        is_select = request.POST.get('is_select')
        nums = request.POST.get('nums')
        # 获取session中商品的信息
        session_goods = request.session.get('goods')
        for goods in session_goods:
            if goods_id == goods[0]:
                # 修改session中的商品的数量和选择状态
                goods[1] = int(nums) if nums else goods[1]
                goods[2] = int(is_select) if is_select else goods[2]
        request.session['goods'] = session_goods
        return JsonResponse({'code': 200, 'msg': '请求成功'})


def del_cart(request, id):
    if request.method == 'GET':
        user_id = request.session.get('user_id')
        if user_id:
            # 登录情况，删除数据库中的数据
            ShoppingCart.objects.filter(user_id=user_id, goods_id=id).delete()
        # 不管登录与否，删除session中的数据
        session_goods = request.session.get('goods')
        for goods in session_goods:
            if goods[0] == int(id):
                session_goods.remove(goods)
        request.session['goods'] = session_goods
        return HttpResponseRedirect(reverse('cart:cart'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
        {% block css %}
        {% endblock %}

        {% block js1 %}
        {% endblock %}
</head>
<body>
    {% block header %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block footer %}
    {% endblock %}

    {% block js2 %}
    {% endblock %}
</body>
</html>

templates/base_main.html
{% extends 'base.html' %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
{% endblock %}

{% block js1 %}
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/static/js/slide.js"></script>
{% endblock %}

{% block header %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到<a href="{% url 'goods:index' %}">天天生鲜</a>!</div>
            <div class="fr">
                {% if request.session.user_id|default:'' != '' %}
                    <div class="login_info fl">
                        欢迎您：<em>{{ user.username }}</em>
                        <span>|</span>
                        <a href="{% url 'goods:logout' %}">退出</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="{% url 'user:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'user:register' %}">注册</a>
                    </div>
                {% endif %}
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'user:user_center_info' %}">用户中心</a>
                    <span>|</span>
                    <a href="{% url 'cart:cart' %}">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'user:user_center_order' %}">我的订单</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    {% block search_bar %}
        <div class="search_bar clearfix">
          {% load static %}
            <a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
            <div class="search_con fl">
                <input type="text" class="input_text fl" name="" placeholder="搜索商品">
                <input type="button" class="input_btn fr" name="" value="搜索">
            </div>
            <div class="guest_cart fr">
                <a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
                <div class="goods_count fl" id="show_count">1</div>
            </div>
        </div>
    {% endblock %}

    {% block navbar_con %}
        <div class="navbar_con">
            <div class="navbar">
                <h1 class="fl">全部商品分类</h1>
                <ul class="navlist fl">
                    <li><a href="{% url 'goods:index' %}">首页</a></li>
                    <li class="interval">|</li>
                    <li><a href="">手机生鲜</a></li>
                    <li class="interval">|</li>
                    <li><a href="">抽奖</a></li>
                </ul>
            </div>
        </div>
    {% endblock %}

    {% block private %}
    {% endblock %}
{% endblock %}

{% block footer %}
    <div class="footer">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="#">联系我们</a>
            <span>|</span>
            <a href="#">招聘人才</a>
            <span>|</span>
            <a href="#">友情链接</a>
        </div>
        <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
        <p>电话：010-****888 京ICP备*******8号</p>
    </div>
{% endblock %}


{% block js2 %}
{% endblock %}



templates/detail.html

{% extends 'base_main.html' %}
{% block title %}
    天天生鲜-商品详情
{% endblock %}

{% block content %}
    {{ block.super }}
    {% block private %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
        <div class="goods_detail_pic fl"><img src="/media/{{ goods.goods_front_image }}"></div>

        <div class="goods_detail_list fr">
            <h3>{{ goods.name }}</h3>
            <p>{{ goods.goods_brief }}</p>
            <div class="prize_bar">
                <span class="show_pirze">¥<em>{{ goods.shop_price }}</em></span>
                <span class="show_unit">单  位：500g</span>
            </div>
            <div class="goods_num clearfix">
                <div class="num_name fl">数 量：</div>
                <div class="num_add fl">
                    <input type="text" class="num_show fl" value="1" onblur="change_val({{ goods.goods_nums }})">
                    <a href="javascript:;" class="add fr" onclick="add_cart({{ goods.goods_nums }})">+</a>
                    <a href="javascript:;" class="minus fr" onclick="sub_cart()">-</a>
                </div>
            </div>
            <div class="total">总价：<em>{{ goods.shop_price }} 元</em></div>
            <div class="operate_btn">
                <a href="javascript:;" class="buy_btn">立即购买</a>
                <a href="javascript:;" class="add_cart" id="add_cart" onclick="add_to_cart({{ goods.id }})">加入购物车</a>
            </div>
        </div>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    <li>
                        <a href="#"><img src="{% static 'images/goods/goods001.jpg' %}"></a>
                        <h4><a href="#">进口柠檬</a></h4>
                        <div class="prize">￥3.90</div>
                    </li>
                    <li>
                        <a href="#"><img src="{% static 'images/goods/goods002.jpg' %}"></a>
                        <h4><a href="#">玫瑰香葡萄</a></h4>
                        <div class="prize">￥16.80</div>
                    </li>
                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <ul class="detail_tab clearfix">
                <li class="active">商品介绍</li>
                <li>评论</li>
            </ul>

            <div class="tab_content">
                <dl>
                    <dt>商品详情：</dt>
                    <dd>{{ goods.goods_desc | safe }}</dd>
                </dl>
            </div>

        </div>
    </div>
 {% endblock %}
{% endblock %}

{% block js2 %}
	<div class="add_jump"></div>

	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript">
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
		$('#add_cart').click(function(){
			$(".add_jump").stop().animate({
				'left': $to_y+7,
				'top': $to_x+7},
				"fast", function() {
					$(".add_jump").fadeOut('fast',function(){
						$('#show_count').html(2);
					});

			});
		})
	</script>
{% endblock %}

templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-登录</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form action="" method="post">
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="password" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

templates/place_order.html

{%  extends 'base_main.html' %}

{% block title %}
    天天生鲜-提交订单
{% endblock %}

{% block content %}
    {% block private %}
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
        <dl>
            <dt>寄送到：</dt>
            {% for user_address in user.useraddress_set.all %}
            <dd><input type="radio" name="address" value="{{ user_address.id }}">{{ user_address.address }} （{{ user_address.signer_name }} 收） {{ user_address.signer_mobile }}</dd>
            {% endfor %}

        </dl>
        <a href="{% url 'user:user_center_site' %}" class="edit_site">编辑收货地址</a>

    </div>

    <h3 class="common_title">支付方式</h3>
    <div class="common_list_con clearfix">
        <div class="pay_style_con clearfix">
            <input type="radio" name="pay_style" checked>
            <label class="cash">货到付款</label>
            <input type="radio" name="pay_style">
            <label class="weixin">微信支付</label>
            <input type="radio" name="pay_style">
            <label class="zhifubao"></label>
            <input type="radio" name="pay_style">
            <label class="bank">银行卡支付</label>
        </div>
    </div>

    <h3 class="common_title">商品列表</h3>

    <div class="common_list_con clearfix">
        <ul class="goods_list_th clearfix">
            <li class="col01">商品名称</li>
            <li class="col02">商品单位</li>
            <li class="col03">商品价格</li>
            <li class="col04">数量</li>
            <li class="col05">小计</li>
        </ul>
        {% for carts in shop_carts %}
        <ul class="goods_list_td clearfix">
            <li class="col01">{{ forloop.counter }}</li>
            <li class="col02"><img src="/media/{{ carts.goods.goods_front_image }}"></li>
            <li class="col03">{{ carts.goods.name }}</li>
            <li class="col04">500g</li>
            <li class="col05">{{ carts.goods.shop_price }}</li>
            <li class="col06">{{ carts.nums }}</li>
            <li class="col07">{{ carts.price }}</li>
        </ul>
        {% endfor %}
    </div>

    <h3 class="common_title">总金额结算</h3>

    <div class="common_list_con clearfix">
        <div class="settle_con">
            <div class="total_goods_count">共<em>{{ carts_count }}</em>件商品，总金额<b>{{ all_total }}</b></div>
            <div class="transit">运费：<b>10元</b></div>
            <div class="total_pay">实付款：<b>{{ all_total | add:10 }}元</b></div>
        </div>
    </div>

    <div class="order_submit clearfix">
        <a href="javascript:;" id="order_btn">提交订单</a>
    </div>
{% endblock %}
{% endblock %}

{% block js2 %}
    <div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>

		<div class="mask"></div>
	</div>
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript">
        $('#order_btn').click(function() {
            localStorage.setItem('order_finish',2);

            address_radio = $('input[name="address"]')
            for (var i=0; i<address_radio.length; i++){
                if(address_radio[i].checked == true){
                    var value = address_radio[i].value
                }
            }
            if(value){
                var csrf = $('input[name="csrfmiddlewaretoken"]').val()
                $.ajax({
                    url: '/order/make_order/',
                    type: 'POST',
                    data: {'address_id': value},
                    dataType: 'JSON',
                    headers: {'X-CSRFToken': csrf},
                    success: function (data) {
                        $('.popup p').text('订单提交成功！')
                    },
                    error: function (data) {
                        $('.popup p').text('订单提交失败！')
                    }
                } )
            }else{
                $('.popup p').text('请选择收货地址！')
            }

            $('.popup_con').fadeIn('fast', function() {
                setTimeout(function(){
                    $('.popup_con').fadeOut('fast',function(){
                        window.location.href = '{% url 'user:user_center_order' %}';
                    });
                },3000)

            });
        });
	</script>
{% endblock %}

templates/register.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>天天生鲜-注册</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
{#    	<script type="text/javascript" src="/static/js/register.js"></script>#}
</head>
<body>
<div class="register_con">
    <div class="l_con fl">
        <a class="reg_logo"><img src="/static/images/logo02.png"></a>
        <div class="reg_slogan">足不出户 · 新鲜每一天</div>
        <div class="reg_banner"></div>
    </div>

    <div class="r_con fr">
        <div class="reg_title clearfix">
            <h1>用户注册</h1>
            <a href="{% url 'user:login' %}">登录</a>
        </div>
        <div class="reg_form clearfix">
            <form action="" method="post">

                <ul>
                    <li>
                        <label>用户名:</label>
                        <input type="text" name="username" id="user_name">
                        <span class="error_tip"> {{ errors.username }}</span>
                    </li>
                    <li>
                        <label>密码:</label>
                        <input type="password" name="password" id="pwd">
                        <span class="error_tip">{{ errors.password }}</span>
                    </li>
                    <li>
                        <label>确认密码:</label>
                        <input type="password" name="cpwd" id="cpwd">
                        <span class="error_tip">{{ errors.pwd2 }}</span>
                    </li>
                    <li>
                        <label>邮箱:</label>
                        <input type="text" name="email" id="email">
                        <span class="error_tip">{{ errors.email }}</span>
                    </li>
                    <li class="agreement">
                        <input type="checkbox" name="allow" id="allow" checked="checked">
                        <label>同意”天天生鲜用户使用协议“</label>
                        <span class="error_tip2">提示信息</span>
                    </li>
                    <li class="reg_sub">
                        <input type="submit" value="注 册">
                    </li>
                </ul>
            </form>
        </div>

    </div>

</div>

<div class="footer no-mp">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>

</body>
</html>

templates/user_center_info.html
{% extends 'base_main.html' %}


{% block title %}
    天天生鲜-用户中心
{% endblock %}

{% block content %}

    {% block private %}
        <div class="main_con clearfix">
        {% load static %}
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'user:user_center_info' %}" class="active">· 个人信息</a></li>
                <li><a href="{% url 'user:user_center_order' %}">· 全部订单</a></li>
                <li><a href="{% url 'user:user_center_site' %}">· 收货地址</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
                <div class="info_con clearfix">
                <h3 class="common_title2">基本信息</h3>
                        <ul class="user_info_list">
                            <li><span>用户名：</span>{{ user.username }}</li>
                            <li><span>联系电话：</span>{{ user.mobile }}</li>
                            <li><span>联系邮箱：</span>{{ user.email }}</li>
                        </ul>
                </div>

                <h3 class="common_title2">最近浏览</h3>
                <div class="has_view_list">
                    <ul class="goods_type_list clearfix">
                <li>
                    <a href="detail.html"><img src="{% static 'images/goods/goods003.jpg' %}"></a>
                    <h4><a href="detail.html">大兴大棚草莓</a></h4>
                    <div class="operate">
                        <span class="prize">￥16.80</span>
                        <span class="unit">16.80/500g</span>
                        <a href="#" class="add_goods" title="加入购物车"></a>
                    </div>
                </li>

                <li>
                    <a href="#"><img src="{% static 'images/goods/goods004.jpg' %}"></a>
                    <h4><a href="#">吐鲁番梨光杏</a></h4>
                    <div class="operate">
                        <span class="prize">￥5.50</span>
                        <span class="unit">5.50/500g</span>
                        <a href="#" class="add_goods" title="加入购物车"></a>
                    </div>
                </li>

                <li>
                    <a href="#"><img src="{% static 'images/goods/goods005.jpg' %}"></a>
                    <h4><a href="#">黄肉桃</a></h4>
                    <div class="operate">
                        <span class="prize">￥10.00</span>
                        <span class="unit">10.00/500g</span>
                        <a href="#" class="add_goods" title="加入购物车"></a>
                    </div>
                </li>

                <li>
                    <a href="#"><img src="{% static 'images/goods/goods006.jpg' %}"></a>
                    <h4><a href="#">进口西梅</a></h4>
                    <div class="operate">
                        <span class="prize">￥28.80</span>
                        <span class="unit">28.8/500g</span>
                        <a href="#" class="add_goods" title="加入购物车"></a>
                    </div>
                </li>

                <li>
                    <a href="#"><img src="{% static 'images/goods/goods007.jpg' %}"></a>
                    <h4><a href="#">香梨</a></h4>
                    <div class="operate">
                        <span class="prize">￥6.45</span>
                        <span class="unit">6.45/500g</span>
                        <a href="#" class="add_goods" title="加入购物车"></a>
                    </div>
                </li>
            </ul>
        </div>
        </div>
    </div>
    {% endblock %}
{% endblock %}

templates/user_center_order.html

{% extends 'base_main.html' %}

{% block content %}
    {% block private %}
	 <div class="main_con clearfix">
     {% load static %}
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'user:user_center_info' %}">· 个人信息</a></li>
                <li><a href="{% url 'user:user_center_order' %}" class="active">· 全部订单</a></li>
                <li><a href="{% url 'user:user_center_site' %}">· 收货地址</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
            <h3 class="common_title2">全部订单</h3>
            {% for order in page %}
                <ul class="order_list_th w978 clearfix">
                    <li class="col01">{{ order.add_time }}</li>
                    <li class="col02">订单号：{{ order.order_sn }}</li>
                    <li class="col02 stress">{{ order.pay_status }}</li>
                </ul>
                <table class="order_list_table w980">
                    <tbody>
                        <tr>
                            <td width="55%">

                                {% for order_goods in order.goods.all %}
                                    <ul class="order_goods_list clearfix">
                                        <li class="col01"><img src="/media/{{ order_goods.goods.goods_front_image }}"></li>
                                        <li class="col02">{{ order_goods.goods.name }}<em>{{ order_goods.goods.shop_price }}元/500g</em></li>
                                        <li class="col03">{{ order_goods.goods_nums }}</li>
                                        <li class="col04">11.80元</li>
                                    </ul>
                                {% endfor %}
                            </td>
                            <td width="15%">{{ order.order_mount }}元</td>
                            <td width="15%">待付款</td>
                            <td width="15%"><a href="#" class="oper_btn">去付款</a></td>
                        </tr>
                    </tbody>
                </table>
            {% endfor %}

                <div class="pagenation">
                    <a href="#">上一页</a>
                    <a href="#" class="active">1</a>
                    <a href="#">2</a>
                    <a href="#">3</a>
                    <a href="#">4</a>
                    <a href="#">5</a>
                    <a href="#">下一页></a>
                </div>
        </div>
    </div>

    {% endblock %}
{% endblock %}